default:
    pattern:  /
    defaults: { _controller: NorteBatimentFrontBundle:Presentation:index }
batiment:
    resource: "@NorteBatimentFrontBundle/Controller/"
    type:     annotation
adminBatimentBundle:
    resource: "@NorteBatimentAdminBundle/Controller/"
    type:     annotation
    prefix:   /secured
    