default:
    pattern:  /
    defaults: { _controller: batimentBundle:Presentation:index }
batiment:
    resource: "@batimentBundle/Controller/"
    type:     annotation
    
adminBatimentBundle:
    resource: "@adminBatimentBundle/Controller/"
    type:     annotation
    