security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    role_hierarchy:
        ROLE_ADMIN:  ROLE_USER
        ROLE_SUPER_ADMIN:  [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        in_memory:
            users:
                francois:  { password: catheline, roles: [ 'ROLE_USER' ] }
                christopher:  { password: catheline, roles: [ 'ROLE_ADMIN' ] }
    firewalls:
        main:
            form_login:
                failure_path: /login_failure
        login_access:
            pattern:  ^/login$
            anonymous:  ~
        secured_area:
            pattern:  ^/
            form_login:  ~
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN}
