<?php

namespace Proxies\__CG__\norte\batimentBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Commentaire extends \norte\batimentBundle\Entity\Commentaire implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setText($text)
    {
        $this->__load();
        return parent::setText($text);
    }

    public function getText()
    {
        $this->__load();
        return parent::getText();
    }

    public function setDate()
    {
        $this->__load();
        return parent::setDate();
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setIsaffiche($isaffiche)
    {
        $this->__load();
        return parent::setIsaffiche($isaffiche);
    }

    public function getIsaffiche()
    {
        $this->__load();
        return parent::getIsaffiche();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIdphoto(\norte\batimentBundle\Entity\Photo $idphoto)
    {
        $this->__load();
        return parent::setIdphoto($idphoto);
    }

    public function getIdphoto()
    {
        $this->__load();
        return parent::getIdphoto();
    }

    public function toJson()
    {
        $this->__load();
        return parent::toJson();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'text', 'date', 'isaffiche', 'id', 'idphoto');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}